### ISSUE TITLE
App crashes after compile...cannot even install

### ISSUE THREAD

**Issue by jagan999** [Skyost/rate_my_app#10]
**Describe the bug**
When I integrated this package into my app and tried to run it in debug mode from VS Code, I cannot even install on my Android device. I verified there's something wrong with this package since my app installs properly as soon as I removed this package from pubspec.yaml and associated references.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Nokia 7.1
 - OS: [e.g. iOS8.1] Android 9

**Additional context**

**Comment by jagan999** [comment]
Looks like it was some random issue with VS Code. It works now. I'm exploring the features as we speak.

**Comment by Skyost** [comment]
Hope you've found what you were searching for :wink:
