### ISSUE TITLE
onRatingChanged doesn't fire when i rate application

### ISSUE THREAD

**Issue by aolSvt** [Skyost/rate_my_app#11]
**Describe the bug**
when i rate app(select stars), i think that onRatingChanged will fire and i can understand the user rate and conditionally do something

```
 _rateMyApp.showStarRateDialog(
      context,
      title: 'Rate this app',
      message: 'You like this app ? Then take a little bit of your time to leave a rating :',
      onRatingChanged: (stars) {
        print('stars - ', stars)
      },
      ignoreIOS: false,
      starRatingOptions: StarRatingOptions(),
    );
```

but **onRatingChanged** doesn't fire when i rate application, or this method will fire only after click on submit button(which disabled in developer mode)?

**Comment by Skyost** [comment]
1. Submit button is not disabledd in dev mode using `showStarRateDialog` (it's only on iOS using the other method, see #1).
2. I think an error occurs (see your Console tab). `onRatingChanged` should return a widget, for instance :

```dart
_rateMyApp.showStarRateDialog(
  context,
  onRatingChanged: (stars) {
    return FlatButton(
      child: Text((stars == null ? '0' : stars.round().toString()) + ' star(s)'),
      onPressed: () => print('stars - ', (stars ?? 0.0)),
    );
  },
);
```

**Comment by aolSvt** [comment]
1. Submit button is only disabled in dev mode on iOS and when ignoreIOS is set to false (using the default iOS rating dialog in fact).

but how i can test default iOS rating dialog(when i set `ignoreIOS` in true  i get custom (for iOs) dialog)?

**Comment by Skyost** [comment]
You set `ignoreIOS` to `false` (default is `false` anyway) and you can test. The only caveat is that you cannot click on "Review" (but it shouldn't be a problem for you as this button will work when you're going to release your app on the App Store).

**Comment by aolSvt** [comment]
thanks!=)
