### ISSUE TITLE
Conditions always met iOS

### ISSUE THREAD

**Issue by OliverNarramore** [Skyost/rate_my_app#15]
**Describe the bug**
I want to display the message after the user has logged in. Therefore, in the page I wish to display it on, I have added the following code outside of the class. 

**To Reproduce**

RateMyApp _rateMyApp = RateMyApp(
  preferencesPrefix: '_rateMyApp',
  minDays: 0,
  minLaunches: 5,
  remindDays: 0,
  remindLaunches: 5,
);

String _dateToString(DateTime date) =>
    date.day.toString().padLeft(2, '0') +
    '/' +
    date.month.toString().padLeft(2, '0') +
    '/' +
    date.year.toString();

then this code inside the stateful widget.

 @override
  void initState() {
    super.initState();

    _rateMyApp.init().then((_) {
      print('Minimum days : ' + _rateMyApp.minDays.toString());
      print('Minimum launches : ' + _rateMyApp.minLaunches.toString());
      print('Remind launches : ' + _rateMyApp.remindLaunches.toString());

      print('Base launch : ' + _dateToString(_rateMyApp.baseLaunchDate));
      print('Launches : ' + _rateMyApp.launches.toString());
      print(
          'Do not open again ? ' + (_rateMyApp.doNotOpenAgain ? 'Yes' : 'No'));

      print('Are conditions met ? ' +
          (_rateMyApp.shouldOpenDialog ? 'Yes' : 'No'));

      if (_rateMyApp.shouldOpenDialog) {
        _rateMyApp.showRateDialog(
          context,
          title: 'Rate this app',
          message:
              'If you like this app, please take a little bit of your time to review it !\nIt really helps us and it shouldn\'t take you more than one minute.',
          rateButton: 'RATE',
          noButton: 'NO THANKS',
          laterButton: 'MAYBE LATER',
          ignoreIOS: false,
        );
      }
    });
}

**Expected behavior**

Despite tapping "not now" the message appears on every launch, rather than every 5 after tapping not now, despite the console correctly displaying the values. "Are Conditions Met" always displays "Yes"

**Smartphone (please complete the following information):**
 - Device: [iPhone6 Plus] running 12.4.1

**Comment by Skyost** [comment]
That's because setting `ignoreIOS` will cause Rate my app to launch the **native** iOS rating dialog. Therefore, Rate my app cannot check which button you've tapped on.

**Comment by Skyost** [comment]
Closed due to no response.
