### ISSUE TITLE
Question: `doNotOpenAgain` after clicking the submit button?

### ISSUE THREAD

**Issue by JonasJW** [Skyost/rate_my_app#18]
This is not a Feature Request nor a Bug.
I was wondering what is the best thing to do after a user clicked on the rate button? He will then be send to the App Store but what should we set `doNotOpenAgain`? We can't be sure if the user actually submitted a rating but if he did, it would be bad to show the dialog again? Whats the best way to handle this?

**Comment by Skyost** [comment]
In my own opinion, you should not show the dialog anymore once the user clicked on _Rate_ or _Cancel_. But it's really your choice :wink:

**Comment by Skyost** [comment]
Closed due to inactivity.
