### ISSUE TITLE
context is undefined 

### ISSUE THREAD

**Issue by jatin-rajput** [Skyost/rate_my_app#19]
if (_rateMyApp.shouldOpenDialog) {
    _rateMyApp.showRateDialog(
      context,
      title: 'Rate this app',
      message: 'If you like this app, please take a little bit of your time to review it !\nIt really helps us and it shouldn\'t take you more than one minute.',
      rateButton: 'RATE',
      noButton: 'NO THANKS',
      laterButton: 'MAYBE LATER',
      ignoreIOS: false,
      dialogStyle: DialogStyle(),
    );
if we placed this code in my app then context is not undefined .. i hope you will be understand ..
and your package is very good and helpfull...please solve this problem..

**Comment by Skyost** [comment]
Yes, because you should pass a `BuildContext` to this function (see [example](https://github.com/Skyost/rate_my_app/blob/master/example/lib/main.dart#L65)).

**Comment by jatin-rajput** [comment]
Ok thanks skyost

**Comment by Skyost** [comment]
No problem :wink:
