### ISSUE TITLE
IOS linking error: -lrate_my_app

### ISSUE THREAD

**Issue by daneed** [Skyost/rate_my_app#20]
Hi!
I have an IOS specific linking error, while building from XCode.
"ld: library not found for -lrate_my_app"
Do you have any idea? I ran flutter pub get, as well as pod install/upgrade/whatever.

**Comment by Skyost** [comment]
> I had a similar "library not found" issue. However it was because I accidentally was using the `.xcodeproj` file instead of the `.xcworkspace` file.

[Source](https://stackoverflow.com/a/28548183/3608831)

**Comment by daneed** [comment]
Hi
Nope, I used .xcworkspace yesterday.
Then today: I tried with .xcodeproj->linkerror (-lFirebasesomething), then I tried again with the .xcworkspace. The lrate_my_app linkerror disappeared. So, I assume that this is a miracle, or whatever. XCode magic or WTF.
But, thanks a lot for your help!
Br, daneed

**Comment by Skyost** [comment]
No problem !
