### ISSUE TITLE
Button text black not visible dark theme (Android)

### ISSUE THREAD

**Issue by matte5031** [Skyost/rate_my_app#21]
Hello!

I use a dark theme (inside ThemeData = brightness: Brightness.dark) on my app and the title and message properties are looking good since they are white. However the rateButton, noButton and laterButton text is black, which the dialog is aswell because of the dark theme, which makes them not visible.

I can't see anyway to change the text color unfortunately, or just handle the dark theme somehow.

Would be great if the showRateDialog could handle flutter dark theme aswell, thanks!

**Comment by Skyost** [comment]
If you try to show a dialog with actions by yourself using `showDialog`, are the actions still not visible ?
