### ISSUE TITLE
App already rated in iOS

### ISSUE THREAD

**Issue by tuanha2000vn** [Skyost/rate_my_app#22]
On Android if you already rated the app, click the button simply go to the store to edit existing rating.

On iOS if you already rated the app, click the button simply do nothing.

Is there any function to know app already rated to hide the button?

In case you install the app on new device but already rated on other device, there no valid data to check doNotOpenAgain, minLaunches, minDays...

Thank you.

**Comment by Skyost** [comment]
You mean like #15 ?

**Comment by tuanha2000vn** [comment]
No, let say scenario like this on iPhone.

1. Download app and install and rate => OK
2. Delete app
3. Download app and install and rate => nothing happen.

**Comment by Skyost** [comment]
It's because of [a known limitation](https://stackoverflow.com/a/51006879/3608831) created by Apple. Nothing you can do about it, sadly.

An alternative may be to set `ignoreIOS` to `false` but at your own risks because Apple may not like if you're not using their native dialog.

**Comment by tuanha2000vn** [comment]
Thank you.

**Comment by Skyost** [comment]
No problem :wink:
