### ISSUE TITLE
Button click listener

### ISSUE THREAD

**Issue by DenchikBY** [Skyost/rate_my_app#25]
Hello!
There is no button click listener on `showRateDialog` like in original Android-Rate library.
It's very useful feature to store click statistics.
It would great if you add it, I see it something like that:
```dart
enum RateDialogButton {
  rate,
  no,
  later,
}

rateMyApp.showRateDialog(
  onClick: (RateDialogButton button) {
  },
);
```

**Comment by Skyost** [comment]
Well in fact, there is a [pull request](https://github.com/Skyost/rate_my_app/pull/23) for that. So I think I'm gonna take care of it today or tomorrow :wink:
