### ISSUE TITLE
Does not callback listener code. ANDROID

### ISSUE THREAD

**Issue by daver123** [Skyost/rate_my_app#28]
Added this code to launch rate me dialog but code never reaches listener code so I have no way to check results of users button clicks. btw, I've added this code to initState

    rateMyApp.init().then((_) {
      if (rateMyApp.shouldOpenDialog) {
        rateMyApp.showRateDialog(
          context,
          title: 'Rate this app',
          message:
              'If you like this app, please take a little bit of your time to review it !\nIt really helps us and it shouldn\'t take you more than one minute.',
          rateButton: 'RATE',
          noButton: 'NO THANKS',
          laterButton: 'MAYBE LATER',
          listener: (button) {
            switch (button) {
              case RateMyAppDialogButton.rate:
                print('Clicked on "Rate".');
                break;
              case RateMyAppDialogButton.later:
                print('Clicked on "Later".');
                break;
              case RateMyAppDialogButton.no:
                print('Clicked on "No".');
                break;
            }
            return true;
          },
          ignoreIOS: false,
          dialogStyle: DialogStyle(),
        );
      }
    });

**Comment by Skyost** [comment]
Your code works fine for me. What version are you using ? There were a bug in 0.4.1 that was fixed in [0.4.1+1](https://pub.dev/packages/rate_my_app#0411).

**Comment by daver123** [comment]
Right was using 0.4.1 so that's likely the issue. I switch to using the star rating which worked perfectly.

**Comment by Skyost** [comment]
Great :wink:
