### ISSUE TITLE
[The setter 'doNotOpenAgain isn't defined for the class 'RateMyApp']

### ISSUE THREAD

**Issue by tiannahenrylewis** [Skyost/rate_my_app#29]
**Describe the bug**
When I attempt to implement .doNotOpenAgain, I get the following error _"The setter 'doNotOpenAgain isn't defined for the class 'RateMyApp'"_.

```
//RateMyApp Preferences
  RateMyApp _rateMyApp = RateMyApp(
    preferencesPrefix: 'rateMyApp_',
    //Minimum number of days a user has to have the app installed, 3
    minDays: 3,
    //Minimum number of launches before showing prompt, 5
    minLaunches: 5,
    //Number of days before requesting a rating, 7
    remindDays: 7,
    //Number of launches before requesting a rating, 5
    remindLaunches: 5,
);
```

    @override
       void initState() {
       super.initState();
       _rateMyApp.init().then((_){
          //if (_rateMyApp.shouldOpenDialog) {
          _rateMyApp.showStarRateDialog(
            context,
            title: 'Enjoying Liquid',
            message: 'Please leave a rating!',
            onRatingChanged: (stars) {
              return [
                FlatButton(
                  onPressed: () {
                    if (stars!= null) {
                      _rateMyApp.doNotOpenAgain = true;
                      _rateMyApp.save().then((v) => Navigator.pop(context));
                      if (stars <= 3) {
                        //Navigate to Contact Screen
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (_) => ContactSupportScreen(),
                          ),
                        );
                      } else if (stars >= 4) {
                        print('Leave a Review');
                      }
                    } else {
                      Navigator.pop(context);
                    }
                  }, //onPressed
                  child: Text('Ok'),
                ),
              ];
            },
            dialogStyle: DialogStyle(
              titleAlign: TextAlign.center,
              messageAlign: TextAlign.center,
              messagePadding: EdgeInsets.only(bottom: 20.0),
            ),
            starRatingOptions: StarRatingOptions(),
          );
          //}
        });
      }
`

**Additional context**
- rate_my_app: ^0.5.0+1

**Comment by Skyost** [comment]
Yes, that's the [new 0.5.0 behavior](https://github.com/Skyost/rate_my_app#broadcasting-events). The condition "Do not open again" can now be removed and therefore this getter/setter is not available anymore.

I see that you want to create a "Rate" button. What you can do is to replace those two lines :

```dart
_rateMyApp.doNotOpenAgain = true;
_rateMyApp.save().then((v) => Navigator.pop(context));
```

By :

```dart
_rateMyApp.callEvent(RateMyAppEventType.rateButtonPressed).then((_) => Navigator.pop(context));
```

The `rateButtonPressed` event will trigger the Do not open again condition (see [here](https://github.com/Skyost/rate_my_app/blob/master/lib/src/conditions.dart#L188)).    
Easier no ? :wink:

**Comment by tiannahenrylewis** [comment]
@Skyost Thanks for clarifying.
