### ISSUE TITLE
hello sir , i tried to use this plugin , but its not opening the dialog after 3 days...

### ISSUE THREAD

**Issue by simra-aulakh** [Skyost/rate_my_app#31]
hello sir , i tried to use this plugin , but its not opening the dialog after 3 days or the times  I have specified the launches .. it works in production when the   if (_rateMyApp.shouldOpenDialog) {  line is uncomment , but its not working when i uncomment it .

**Comment by simra-aulakh** [comment]
class _DashboardScreenState extends State<DashboardScreen> {
  RateMyApp _rateMyApp = RateMyApp(
    preferencesPrefix: 'rateMyApp_',
    minDays: 3,
    minLaunches: 7,
    remindDays: 2,
    remindLaunches: 5,
  );

  @override
  void initState() {
    super.initState();
_rateMyApp.init().then((_) {
      if (_rateMyApp.shouldOpenDialog) {
        _rateMyApp.showStarRateDialog(
          context,
          title: 'Enjoying Our App?',
          message: 'Please leave a rating!',
          onRatingChanged: (stars) {
            return [
              RaisedButton(
                padding: EdgeInsets.symmetric(horizontal: 22.0, vertical: 6.0),
                color: Colors.red,
                child: Text('Rate'),
                textColor: Colors.white,
                highlightElevation: 2,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10),
                ),
                onPressed: () {
                  if (stars != null) {
                    _rateMyApp
                        .callEvent(RateMyAppEventType.rateButtonPressed)
                        .then((_) => Navigator.pop(context));
                    if (stars <= 3) {
                      Navigator.of(context).pop();
                    } else if (stars <= 5) {
                      _rateURL();
                    }
                  } else {
                    Navigator.pop(context);
                  }
                },
              ),
            ];
          },
          dialogStyle: DialogStyle(
            titleAlign: TextAlign.center,
            messageAlign: TextAlign.center,
            messagePadding: EdgeInsets.only(bottom: 20.0),
          ),
          starRatingOptions: StarRatingOptions(),
        );
      }
    });

**Comment by simra-aulakh** [comment]
RateMyApp rateMyApp = RateMyApp(
    preferencesPrefix: 'rateMyApp_',
    //minDays: 7,
    minLaunches: 1,
    //remindDays: 7,
    //remindLaunches: 10,
  );

**Comment by Skyost** [comment]
First, you should not do UI operations in `initState`. Please wrap the code inside something like this :

```dart
SchedulerBinding.addPostFrameCallback((_) {
  // Code here.
});
```

Second, do you have any error ? And what is your platform ?

Oh and I see there are more conditions than just waiting 3 days. You must have launched your app at least 7 times.

**Comment by simra-aulakh** [comment]
is there any way i can contact you . i dont have any issue and there is no bug in your plugin .
honestly i was asking how to implement it . thanks .sorry for botheration .

**Comment by Skyost** [comment]
No problem, feel free to ask your question here as it may help someone else :wink:

**Comment by simra-aulakh** [comment]
i am not able to apply this plugin sir , 
i followed tutorial of marcus as well on utube , but it works in production . not in release. i had uncomment the line as well , but it doesn't opens. Sir, I need proper guidance on how to apply it . thanks

**Comment by Skyost** [comment]
I see there are more conditions than just waiting 3 days. You must have launched your app at least 7 times.
