### ISSUE TITLE
iOS: incorrect dark theme support

### ISSUE THREAD

**Issue by YarMag** [Skyost/rate_my_app#32]
When shown on device using dark theme, dialog's text is drawn according to dark theme, while its background is still belonging to light one. See screenshot attached.

![Screenshot 2020-01-09 at 09 32 43](https://user-images.githubusercontent.com/23014470/72043919-89322d80-32c3-11ea-8e3a-b111f96affe7.png)

Expected behavior - dialog background should be black.

Tested on simulator:
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.0

**Comment by Skyost** [comment]
Unfortunately, Rate my app has no control on your specified dialog as it's the native iOS rating dialog. You may find some useful info [here](https://stackoverflow.com/q/57763132/3608831).

**Comment by YarMag** [comment]
Got it, thanks!
