### ISSUE TITLE
iOS Darkmode Background is white

### ISSUE THREAD

**Issue by eifachtimon** [Skyost/rate_my_app#33]
On iOS is the title and message from the default iOS promt are white. **But** the background of the promt is also white instead of dark grey.

**Comment by Skyost** [comment]
Please provide a screenshot.

**Comment by eifachtimon** [comment]
Here some Screenshots :)

![IMG_3179](https://user-images.githubusercontent.com/47282620/72185109-576bb480-33f2-11ea-9348-6dc252349196.PNG)

video: [https://drive.google.com/file/d/1ZhZ1vu4ye1YH_F-BwihhbqpAeWMF3yGE/view?usp=sharing](url)

**Comment by Skyost** [comment]
Duplicate of #32 I think.

**Comment by eifachtimon** [comment]
Oh yes. It's fixed in iOS 13.3.
Thanks!

**Comment by Skyost** [comment]
No problem :wink:
