### ISSUE TITLE
Exception on pressing any button

### ISSUE THREAD

**Issue by imhafeez** [Skyost/rate_my_app#35]
**Describe the bug**

**when the dialog shows it through exception on pressing any button.**

`E/flutter (18056): #18     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:101
E/flutter (18056): #19     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:218
E/flutter (18056): #20     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (18056): #21     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (18056): #22     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (18056): #23     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (18056): #24     _rootRunUnary  (dart:async/zone.dart:1138:13)
E/flutter (18056): #25     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter (18056): #26     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter (18056): #27     _invoke1  (dart:ui/hooks.dart:273:10)
E/flutter (18056): #28     _dispatchPointerDataPacket  (dart:ui/hooks.dart:182:5)`
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Skyost** [comment]
You can't call `Navigator.pop` with your current context don't you ? Please post the source code just to be sure.
