### ISSUE TITLE
shouldOpenDialog is always false. Please help if there is something I am doing wrong.

### ISSUE THREAD

**Issue by japatel225** [Skyost/rate_my_app#5]
This is how I am using this plug-in in my flutter app.

`class Home extends StatefulWidget{
HomeState createState() => HomeState();
}

class HomeState extends State with TickerProviderStateMixin{

RateMyApp _rateMyApp = RateMyApp(
minDays: 1,
minLaunches: 2,
remindDays: 1,
remindLaunches: 2,
);

void initState(){
rateMyApp.init().then(() {
if (_rateMyApp.shouldOpenDialog) {
_rateMyApp.showRateDialog(
context,
title: 'Rate this app',
message: 'If you like this app, please take a little bit of your time to review it !\nIt really helps us and it shouldn't take you more than one minute.',
rateButton: 'RATE',
noButton: 'NO THANKS',
laterButton: 'MAYBE LATER',
);
}
});
}

Widget build(BuildContext context){
}

}`

I have displayed the value of __rateMyApp.shouldOpenDialog_ in a text widget in my UI for testing, and it is always false, which should be true after 2 launches. Because it is always false, the rate-dialog is never appearing. Is there something I am doing wrong?

**Comment by Skyost** [comment]
Hey, try with `minDays: 0` instead :wink:

**Comment by japatel225** [comment]
hey, thank you so much for the fast reply. I think I misunderstood how the parameters worked internally. :)

So it checks for both criteria right? _minDays_ AND _minLaunches_ right? I thought it worked like either _minDays_ OR _minLaunches_ condition should satisfy and it will result in "true".

So now I did this setup 
_minDays: 0,
minLaunches: 5,
remindDays: 7,
remindLaunches: 5_

And it is working. It did show the dialog on 5th launch. And I hit "MAYBE LATER". After this, it is showing the dialog on every launch. Because _remindLaunches_ is 5, shouldn't it now show the dialog on the 10th launch?

**Comment by Skyost** [comment]
Yes it checks for both criterias. There was a bug affecting `0.2.0+2` users clicking _Maybe Later_. This bug was affecting the `remindLaunches` parameter.

I've just published a release because there was also a bug affecting `remindDays` parameter. So please try with the `0.2.0+4` release :wink:

**Comment by japatel225** [comment]
Hi, thanks :) _maybe-later_ is working as intended in 0.2.0+4. I have the below setup

_minDays: 0,
minLaunches: 2,
remindDays: 0,
remindLaunches: 2,_

and it is showing dialog as intended on every second launch with _maybe-later_ .

However, there is another problem. What I observed is - when I dismiss the dialog by tapping outside of the dialog, it makes the _maybe-later_ "not working" for as many times as I dismiss the dialog by tapping outside of the dialog. For example, if I dismiss the dialog 3 times by tapping outside of the dialog, then _maybe-later_ does not work as intended for the next 3 times. And starts working as intended from the 4th time.

**Comment by Skyost** [comment]
Ok, a raw solution is to prevent the dialog from being dismissed like this.

**Comment by Skyost** [comment]
Your help is greatly appreciated by the way !

**Comment by japatel225** [comment]
Hi, yes I was trying this here

 _rateMyApp.showRateDialog(
          context,
          _barrierDismissible: false,_
          title: 'Rate this app',

but it was invalid. So should I make the change in the _rate_my_app_ plugin's file in my project?

**Comment by Skyost** [comment]
Sadly, you'll have to wait for the new release (in this new release, [`628a142`](https://github.com/Skyost/rate_my_app/commit/628a1421075297b331a0e6a4e36f73cb95776357) will be effective).

I'm just waiting to do a couple more changes to publish this release so if you have any idea... :wink:

**Comment by japatel225** [comment]
Hi, how can you get this commit [https://github.com/Skyost/rate_my_app/commit/628a1421075297b331a0e6a4e36f73cb95776357](url) in my project?

**Comment by japatel225** [comment]
> 
> 
> Sadly, you'll have to wait for the new release (in this new release, [`628a142`](https://github.com/Skyost/rate_my_app/commit/628a1421075297b331a0e6a4e36f73cb95776357) will be effective).
> 
> I'm just waiting to do a couple more changes to publish this release so if you have any idea... wink

Hi, whats up? :) Are you going to publish the new release soon?

**Comment by Skyost** [comment]
I'm on another project for the moment, this release has a low priority for the moment. But what you can do if you want to add this manually in your project is (with Android Studio) go to _External libraries_, then expand the _Flutter plugins_ tree, select *rate_my_app* and here you can edit the library locally.

**Comment by japatel225** [comment]
okay, thanks. I'll do that.

**Comment by Skyost** [comment]
No problem. :wink:
