### ISSUE TITLE
Show rating stars on android or at least an option to hide or show them as in IOS

### ISSUE THREAD

**Issue by hexdump2002** [Skyost/rate_my_app#6]
**Is your feature request related to a problem? Please describe.**
On Android, the dialog shown is just a text with several buttons.

**Describe the solution you'd like**
It would be nice to let the user rate the app in this dialog (Show a star rater widget). This way we can decide what to do depending on what should do the user when reviewing it on the store.

For example I would like to make the user send me and email when he is going to rate the app with 3 or less stars.

**Describe alternatives you've considered**
This is the only lib I like. 

**Additional context**
Not needed

**Comment by Skyost** [comment]
I think an option would be to create a method called `showStarRateDialog`, and the dialog would be as described.

Great idea ! :wink:

**Comment by hexdump2002** [comment]
Well, best ideas are the ones that are built around a need :). Hope you could implement it. Cheers!
