### ISSUE TITLE
Anything needed to code on "OK" button press for rate app

### ISSUE THREAD

**Issue by Jigneshiosdeveloper** [Skyost/rate_my_app#7]
Hi, I just want to know that i am using your showStarRateDialog in my app and i found that code once you click OK button after rating at that time SnackBar will display and popup will disappear. so my questions are below:
(1) The Rating will reflect on Review section of app (Play Store & Appstore) or any code i need to put on "OK" button click.
(2) if any user wants to write some review for app so how can write in this popup?  if any feature will come to write review for same.

**Comment by Skyost** [comment]
1. No, the use of `showStarRateDialog` is basically to let you decide what action you want to do based on the rating. For instance if the user gives 1 or 2 stars, take him to your contact page and if he gives more stars then take him to the app review page.
2. Well, I don't think I've perfectly understood your question but you can create a `ReviewDialog` for example and then :

```dart
_rateMyApp.showStarRateDialog(
  context,
  onRatingChanged: (stars) {
    List<Widget> result = [
      FlatButton(
        child: Text('Cancel'),
        onPressed: () {
            Navigator.pop(context);
        },
      ),
    ];
    if (stars != null) {
      result.add(
        FlatButton(
          child: Text('Cancel'),
          onPressed: () {
            Navigator.pop(context);
            // Open the ReviewDialog.
          },
        ),
      );
    }
    return result;
  },
  ignoreIOS: false,
);
```

**Comment by Jigneshiosdeveloper** [comment]
Thanks for reply. My question is that i am going to upload app on play store so after releasing app and once it will live. if user comes on app and popup showStarRateDialog and will give rating on it. so can i see that rating in my live app review & rating section.

or i need to code for redirect review page of my app in play store ( code needed on "OK" Press of showStarRateDialog) because your code Navigator.pop(context); on "OK" press button.
